name: K9_Karaoke
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sound_platform_interface: ^8.4.2
  #flutter_ffmpeg: ^0.3.1
  #flutter_ffmpeg: ^0.4.2
  flutter_sound: ^8.4.2
  #flutter_sound_lite: ^5.0.1
  ## flutter_sound: ^6.1.4
  #sounds: ^1.0.0-beta.13
  ## sounds: ^0.9.3
  intl: ^0.17.0
  # uuid: ^2.0.4
  uuid: ^3.0.5
#  http: ^0.13.4
  http: 0.13.5
#  provider: ^4.0.4
  provider: ^6.0.1
  # path_provider: ^1.6.0
  path_provider: ^2.0.8
  # webview_flutter: ^0.3.19+8
  webview_flutter: ^3.0.0
  #flutter_spinkit: ^4.1.2
  flutter_spinkit: ^5.1.0
  outline_material_icons: ^0.1.1
  csv: ^5.0.1
  image_cropper: ^1.4.1
  openid_client: ^0.4.3
  url_launcher: ^6.0.17
  url_launcher_platform_interface: ^2.0.4
  plugin_platform_interface: ^2.0.2
  dio: ^4.0.4
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  # flutter_auth_buttons: ^0.8.0
  auth_buttons: ^2.0.3
  shared_preferences: ^2.0.11
  storage_path: ^0.2.0
 # line_awesome_icons: ^1.0.4+2
  font_awesome_flutter: ^9.2.0
  permission_handler: ^8.3.0
  image_picker: ^0.8.4+4
  flutter_facebook_login: ^3.0.0
  # flutter_login_facebook: ^1.4.1
  cupertino_icons: ^1.0.4
  image: ^3.1.0
  share: ^2.0.4
  flutter_keyboard_visibility: ^5.1.0
  # carousel_slider: ^2.2.1
  #carousel_slider:
  #  git:
  #    url: https://github.com/handofthecode/flutter_carousel_slider.git
  sentry: ^6.2.2
  flutter_svg: ^1.0.0
  airplane_mode_detection: ^1.0.0
  connectivity: ^3.0.6
  purchases_flutter: ^3.8.0
  email_validator: '^2.0.1'
  file_picker: ^3.0.4
  sign_in_with_apple: ^4.0.0
  firebase_core:
  firebase_auth:
  firebase_messaging_platform_interface: 3.1.6
  google_sign_in:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/k9_logo.jpg"
  min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - credentials/gcloud_credentials.json
    - assets/backgrounds/
    - assets/fonts/
    - assets/card_frames/
    - assets/sounds/
    - assets/images/

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icon_font.ttf
    - family: Museo
      fonts:
        - asset: assets/fonts/museo-sans-rounded-700.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

module:
  androidX: true