/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData modal_logout = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData modal_mailbox = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData modal_paws_bottomright = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData modal_paws_topleft = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData modal_trashcan = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData modal_share = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_library = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_left = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_right = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_list_options = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_list_play = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData song_quick = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData social_facebook = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData social_instagram = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData social_twitter = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_cancel = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aa = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData draw = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hambooger_close = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hambooger = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_icon = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData media_controls_play = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData media_controls_record = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData media_controls_stop = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_list_stop = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snap_quick = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData highlight = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData style_quick = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speak_quick = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
